name: 'cost_management_asset_dbt'
version: '1.0.0'
config-version: 2

profile: 'cost_management_asset_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  cost_management_asset_dbt:
    intermediate:
      +schema: intermediate
      +materialized: view
    curated:
      +schema: refined
      +materialized: table


